receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ${env:TEMPO_URL}
    tls:
      insecure: true
  otlp/dashboard:
    endpoint: ${env:DASHBOARD_URL}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, otlp/dashboard]
      # exporters: [otlp, oltphttp, debug]