receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  otlp/2:
    endpoint: host.docker.internal:4007
    tls:
      insecure: true
  otlp/dashboard:
    endpoint: host.docker.internal:16016
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/2, otlp/dashboard]
      # exporters: [otlp, oltphttp, debug]