receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:4007
    tls:
      insecure: true
  otlphttp:
    endpoint: http://localhost:4008
    tls:
      insecure: true

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      # exporters: [otlp, oltphttp, debug]